### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Poea** [timetocode/nengi#1]
![image](http://i.imgur.com/3WaIfhR.png) get this error when trying to run negi

**Comment by NateTheGreatt** [comment]
First, make sure you have both NPM and Node up to date. My NPM is v4.5.0, and I'm not sure what Node version is required but I have v7.7.4.

**Comment by MonkBliss** [comment]
![image](http://i.imgur.com/YCh3vB5.png) @timetocode

**Comment by timetocode** [comment]
I'm not sure the specific cause of this error. I received a similar error once that I think was fixed by installing python and a c++ compiler. There's a one-liner that can do this via npm. 

https://www.npmjs.com/package/windows-build-tools
npm install --global windows-build-tools
