### ISSUE TITLE
onConnect missing from types

### ISSUE THREAD

**Issue by 0x-General** [timetocode/nengi#25]
I see this line (https://github.com/timetocode/nengi/blob/bf6ea87f5c1c91e3f3c762bb3f9f3dbab3e2c97b/index.d.ts#L89) has been commented out as none of these methods are intended for public consumption. Yet I see them being used in some of the examples (https://github.com/timetocode/nengi-babylon-3d-shooter/blob/master/server/niceInstanceExtension.js#L3 & https://github.com/timetocode/3d-top-down/blob/master/server/GameInstance.js#L17). I think I'm missing something here. Are these methods really meant to be commented out or is it being misused in the examples?

Also, I believe the `onConnect` type definition is missing from here https://github.com/timetocode/nengi/blob/master/index.d.ts#L133. Is it correct?

**Comment by timetocode** [comment]
You are correct that the type definitions are missing/incorrect. Instance certainly has an `onConnect` intended for public consumption, as well as an `onDisconnect`.  I'll update the typescript definitions asap.

**Comment by timetocode** [comment]
Added some typescript enhancements, version 1.23.0. Thanks!
https://github.com/timetocode/nengi/commit/a0c2ca4b22ea21cbb4f90ebab0d3557087c17010#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8

**Comment by 0x-General** [comment]
Thanks!
