### ISSUE TITLE
Bots do not receive messages

### ISSUE THREAD

**Issue by ra1ngo** [timetocode/nengi#26]
Was that intended or did I set up nengi incorrectly?

**Comment by timetocode** [comment]
I think bots should be able to read messages, though I haven't used that feature in awhile.

The bots mostly mirror the `Client` part of the api -- so a call to `bot.readNetwork()` should return a snapshot with any game state. If this still doesn't work let me know and I'll take a look at the bots.

Also if you'd like, there's a nengi discord server that people check pretty frequently for support-related stuff:  https://discord.com/invite/7kAa7NJ
