### ISSUE TITLE
node version / module.link is not a function

### ISSUE THREAD

**Issue by micktaiwan** [timetocode/nengi#28]
What node version does nengi uses ?
On this [page](https://www.npmjs.com/package/nengi) it says it runs with node 14, but when using it with Meteor (using Node 14) it throws this error:
```
/node_modules/nengi/index-es6.js:1
TypeError: module.link is not a function
```

**Comment by micktaiwan** [comment]
I solved it by adding
```
    "type": "module",
    "main": "index-es6.js",
```
to `package.json`

**Comment by ddaydd** [comment]
you probably meant `package.json`
