### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by ansien** [timetocode/nengi#7]
Any plans for Typescript definitions or "native" Typescript support?

Awesome engine btw!

**Comment by timetocode** [comment]
I don't know a whole lot about typescript. Is this something that I can reasonably add without porting nengi to typescript? I'd be open to adding some definitions if easy

**Comment by ansien** [comment]
Yes. Typescript is a superset of Javascript so in theory you can just change the file extensions to .ts and run the compiler. TypeScript would be a massive improvement for the engine because of all the added type safety.

**Comment by shunia** [comment]
Change the source code from `js` into `ts` is not required, you can keep the source code as is with definition files alongside: 
http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

Or just take a look at how `pixi.js` does this:
https://github.com/pixijs/pixi-typescript

FYI

**Comment by timetocode** [comment]
I'm going to close this as there is a fair amount of typescript support at the moment. It should be noted that while one can now make a typescript game in nengi, there is a a tricky area (where the types mutate, aka dynamic code).

The main issue is the creation of objects by nengi with the expectation that the game developer adds properties to the object (e.g. the client object created by the server on connection). What "type" is an object if its shape changes..? To formally handle this one needs to use an intersection type (maybe?) or fork nengi and add desired properties to the types in question. Technically this happens all over nengi but this client objects end being the only real concern I've heard from typescript users. So to reiterate my recommendations are to see if you can get what you need from interface extension or intersections or other advanced features (https://www.typescriptlang.org/docs/handbook/advanced-types.html). Worst case scenario, fork nengi and add some typed props.

In the next major release (whichever one has fundamental API changes) I will be evaluating whether the most dynamic sections of the nengi api can be redone in a manner that is fully static, thus allowing for a typed paradigm without any deliberate use of advanced types. It seems likely that this will be possible, as nengi, despite not being made in typescript, is fundamentally about "typing" properties as binary and sending them across the network. It happens to be highly dynamic and itself mutates types and object shapes, but what it actually exposes to the game code is often very static in shape.
